"""
Migrate OWASP Top 10 for LLM Applications codes from the 2025 edition to 2026.

The 2026 edition (published 2026-08-03) is a RENUMBERING plus one rename:
no entry was added and none removed, so the 2025 -> 2026 mapping is a
bijection over LLM01-LLM10. The crosswalk lives in
mappings/owasp_llm_2025_to_2026.json and is read from there; this script
hardcodes no permutation of its own.

WHY THIS NEEDS A GUARD
----------------------
The code space is IDENTICAL before and after (LLM01-LLM10), so
schema/incident.schema.json validates a correctly-migrated file and a
doubly-migrated file equally happily. Applying the permutation twice
silently corrupts every mapping with no error anywhere in the build. This
script therefore refuses to run against inputs it has already migrated,
using the stamp file data/.owasp_llm_migration.json (SHA-256 per file).

WHAT IT TOUCHES
---------------
Build INPUTS only. data/incidents.json, data/incidents.min.json and
data/legacy_consolidated.json are BUILD OUTPUTS regenerated by `make build`
from these inputs -- they are never hand-edited here (project invariant:
never hand-edit data/*.json).

  legacy/incidents.json    owasp_entries[] entries matching LLM\\d\\d
                           (DSGAI* codes in the same array are left alone)
  ingest/*.json            owasp_llm[]

SCOPE
-----
Code renumbering ONLY. Each entry keeps the risk concept it was already
assigned; only the identifier for that concept changes. Several 2026
entries widened their scope, but incidents that would newly qualify are NOT
added: that is re-classification, which requires re-running classifiers over
incident descriptions, and description-coupled reclassification is a known
hazard in this repo (docs/audits/WS0-T3-cascade-2026-07-18.md). Any such
additions are annotation work under WS2, not part of this migration.

Usage:
  python scripts/migrate_owasp_llm_2026.py            # dry run + delta report
  python scripts/migrate_owasp_llm_2026.py --apply    # write files + stamp
  python scripts/migrate_owasp_llm_2026.py --verify data/incidents.json
"""

from __future__ import annotations

import argparse
import copy
import glob
import hashlib
import json
import re
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CROSSWALK_PATH = ROOT / "mappings" / "owasp_llm_2025_to_2026.json"
STAMP_PATH = ROOT / "data" / ".owasp_llm_migration.json"
MIGRATION_ID = "owasp_llm_2025_to_2026"

LLM_CODE_RE = re.compile(r"^LLM\d{2}$")


# --------------------------------------------------------------------------
# crosswalk
# --------------------------------------------------------------------------
def load_crosswalk() -> dict[str, str]:
    raw = json.loads(CROSSWALK_PATH.read_text(encoding="utf-8"))
    cw = {old: spec["to"] for old, spec in raw["crosswalk"].items()}
    if sorted(cw) != sorted(cw.values()):
        raise SystemExit(
            "FATAL: crosswalk is not a bijection over its own key set; "
            f"domain={sorted(cw)} image={sorted(cw.values())}"
        )
    if len(set(cw.values())) != len(cw):
        raise SystemExit("FATAL: crosswalk maps two 2025 codes onto one 2026 code")
    return cw


# --------------------------------------------------------------------------
# surgical text transform
#
# The ingest snapshots were written by different scripts over time and do not
# share one json.dumps() form -- several use a compact style that puts scalar
# arrays on a single line. Round-tripping those through json.dumps() rewrites
# the entire file (70KB of diff to express a 100-byte change), burying the
# actual delta and destroying review signal.
#
# So the WRITE is done on raw text: only the code tokens inside owasp_llm /
# owasp_entries arrays are rewritten, and every byte of formatting is left
# exactly as found. The VERIFY is still done on parsed JSON (field_delta
# below), so correctness is not being traded away for tidiness.
#
# `[^\]]*` is safe here because both arrays hold only strings -- there is no
# nested bracket to run past. assert_no_nesting() enforces that per file.
# --------------------------------------------------------------------------
ARRAY_RE = re.compile(r'("(?:owasp_llm|owasp_entries)"\s*:\s*\[)([^\]]*)(\])')
CODE_TOKEN_RE = re.compile(r'"(LLM\d{2})"')


def assert_no_nesting(obj, rel: str) -> None:
    """Guard the [^\\]]* assumption: these arrays must contain only strings."""
    def walk(n):
        if isinstance(n, dict):
            for k, v in n.items():
                if k in ("owasp_llm", "owasp_entries") and isinstance(v, list):
                    for x in v:
                        if not isinstance(x, str):
                            raise SystemExit(
                                f"FATAL: {rel}: {k} holds a non-string ({type(x).__name__}); "
                                "the text-level transform is not safe here"
                            )
                else:
                    walk(v)
        elif isinstance(n, list):
            for v in n:
                walk(v)
    walk(obj)


def transform_text(raw: str, cw: dict[str, str], stats: Counter) -> str:
    def fix_array(m: re.Match) -> str:
        def fix_code(t: re.Match) -> str:
            old = t.group(1)
            if old not in cw:
                raise SystemExit(f"FATAL: {old} is not in the crosswalk")
            stats[f"{old}->{cw[old]}"] += 1
            return f'"{cw[old]}"'
        return m.group(1) + CODE_TOKEN_RE.sub(fix_code, m.group(2)) + m.group(3)

    return ARRAY_RE.sub(fix_array, raw)


# --------------------------------------------------------------------------
# field-level delta (working agreement 2)
#
# Walks every entry before and after and reports which FIELDS changed. A
# migration that claims to touch only owasp_llm but moves any other field is
# a defect, and this is what surfaces it.
# --------------------------------------------------------------------------
def entries_of(obj):
    if isinstance(obj, dict) and isinstance(obj.get("incidents"), list):
        return obj["incidents"]
    if isinstance(obj, list):
        return obj
    return []


def field_delta(before, after) -> tuple[Counter, list[str]]:
    changed = Counter()
    problems: list[str] = []
    eb, ea = entries_of(before), entries_of(after)
    if len(eb) != len(ea):
        problems.append(f"ENTRY COUNT CHANGED: {len(eb)} -> {len(ea)}")
        return changed, problems
    for i, (b, a) in enumerate(zip(eb, ea)):
        if not isinstance(b, dict) or not isinstance(a, dict):
            continue
        if set(b) != set(a):
            problems.append(f"entry #{i}: field SET changed: {set(b) ^ set(a)}")
        for k in set(b) | set(a):
            if b.get(k) != a.get(k):
                changed[k] += 1
    return changed, problems


def id_set(obj) -> set:
    out = set()
    for e in entries_of(obj):
        if isinstance(e, dict):
            for key in ("id", "source_id"):
                if e.get(key):
                    out.add(f"{key}:{e[key]}")
                    break
    return out


def census(obj) -> Counter:
    c = Counter()

    def walk(n):
        if isinstance(n, dict):
            for k, v in n.items():
                if k in ("owasp_llm", "owasp_entries") and isinstance(v, list):
                    c.update(x for x in v if isinstance(x, str) and LLM_CODE_RE.match(x))
                else:
                    walk(v)
        elif isinstance(n, list):
            for v in n:
                walk(v)

    walk(obj)
    return c


# --------------------------------------------------------------------------
# data/incidents.json is a build OUTPUT, but it is also a genuine build INPUT
# for one path: merge_and_dedupe.py's retain-on-drop step
# (load_retained_priors(), docs/superpowers/specs/2026-06-01-retain-on-drop-design.md).
# Entries every source has dropped are carried VERBATIM out of the previous
# data/incidents.json so the never-delete invariant holds. Those rows are not
# re-derived from any ingest feed, so an inputs-only migration cannot reach
# them: they would keep 2025 codes through every future rebuild. Measured on
# this migration: 9 retained rows, 16 code assignments, which showed up as a
# 9-entry drift between the migrated build and the crosswalk image of the
# pre-migration build.
#
# This is NOT a hand-edit of data/*.json -- that invariant forbids editing the
# built corpus by hand, and this is a deterministic, delta-verified script.
# It must run BEFORE `make build`, on the pre-migration file.
RETENTION_SOURCE = ROOT / "data" / "incidents.json"


def targets() -> list[Path]:
    out = [ROOT / "legacy" / "incidents.json", RETENTION_SOURCE]
    out += sorted(Path(p) for p in glob.glob(str(ROOT / "ingest" / "*.json")))
    return [p for p in out if p.exists()]


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def load_stamp() -> dict:
    if STAMP_PATH.exists():
        return json.loads(STAMP_PATH.read_text(encoding="utf-8"))
    return {}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="write files (default: dry run)")
    ap.add_argument("--force", action="store_true", help="override the double-apply guard")
    ap.add_argument("--verify", metavar="FILE", help="check a built file for 2026 codes")
    ap.add_argument("--report", metavar="FILE", help="write the delta report to FILE")
    args = ap.parse_args()

    cw = load_crosswalk()

    if args.verify:
        return verify(Path(args.verify), cw)

    stamp = load_stamp()
    already = stamp.get("migrations", {}).get(MIGRATION_ID, {})

    lines: list[str] = []
    total = Counter()
    grand_before = Counter()
    grand_after = Counter()
    all_problems: list[str] = []
    planned: list[tuple[Path, str, str]] = []  # path, new_text, sha_before

    for path in targets():
        # newline="" preserves whatever endings the file already uses, so the
        # write can reproduce them byte-for-byte instead of normalizing them.
        with open(path, encoding="utf-8", newline="") as fh:
            raw = fh.read()
        obj = json.loads(raw)
        before = copy.deepcopy(obj)

        pre = census(obj)
        if not pre:
            continue

        sha_before = sha256(path)
        rel = path.relative_to(ROOT).as_posix()

        # Double-apply guards. A permutation applied twice is silently wrong,
        # and nothing downstream can detect it, so both guards fail CLOSED.
        if not args.force:
            # (a) byte-identical to what this migration last produced.
            prev = already.get(rel)
            if prev and prev.get("sha256_after") == sha_before:
                print(f"[skip] {rel}: already migrated (sha matches stamp)")
                continue
            # (b) semantic guard for the retention source. It is rewritten by
            # every `make build`, so its sha will not match the stamp after a
            # rebuild -- but by then it already holds 2026 codes. The dataset
            # description merge_and_dedupe.py stamps into it names the edition,
            # so use that rather than a hash.
            if path == RETENTION_SOURCE and "OWASP LLM Top 10 (2026)" in raw:
                print(f"[skip] {rel}: already declares the 2026 edition")
                continue

        assert_no_nesting(obj, rel)
        stats = Counter()
        new_raw = transform_text(raw, cw, stats)
        try:
            obj = json.loads(new_raw)
        except json.JSONDecodeError as exc:
            print(f"FATAL: {rel}: transform produced invalid JSON: {exc}", file=sys.stderr)
            return 1
        post = census(obj)

        changed, problems = field_delta(before, obj)
        ids_before, ids_after = id_set(before), id_set(obj)
        if ids_before != ids_after:
            problems.append(
                f"ID SET CHANGED: +{len(ids_after - ids_before)} -{len(ids_before - ids_after)}"
            )
        unexpected = {k: v for k, v in changed.items() if k not in ("owasp_llm", "owasp_entries")}
        if unexpected:
            problems.append(f"UNEXPECTED FIELD CHANGES: {unexpected}")
        if sum(pre.values()) != sum(post.values()):
            problems.append(
                f"CODE COUNT CHANGED: {sum(pre.values())} -> {sum(post.values())}"
            )
        # The text transform must change ONLY code tokens. Any length change
        # beyond that is formatting drift and a defect.
        if len(new_raw) != len(raw):
            problems.append(
                f"BYTE LENGTH CHANGED: {len(raw)} -> {len(new_raw)}; the transform "
                "should be length-preserving (all codes are 5 chars)"
            )

        grand_before.update(pre)
        grand_after.update(post)
        total.update(stats)
        all_problems += [f"{rel}: {p}" for p in problems]

        lines.append(f"### `{rel}`")
        lines.append("")
        lines.append(f"- entries: {len(entries_of(before))} (unchanged)")
        lines.append(f"- code assignments: {sum(pre.values())} -> {sum(post.values())}")
        lines.append(f"- fields changed: {dict(changed) or 'none'}")
        lines.append("")
        lines.append("| code | before | after |")
        lines.append("|---|---:|---:|")
        for code in sorted(set(pre) | set(post)):
            lines.append(f"| {code} | {pre.get(code, 0)} | {post.get(code, 0)} |")
        lines.append("")
        if problems:
            lines.append("**PROBLEMS**")
            for p in problems:
                lines.append(f"- {p}")
            lines.append("")

        planned.append((path, new_raw, sha_before))

    # ---- aggregate check: the image of the before-census under the crosswalk
    # must equal the after-census exactly. This is the whole migration in one
    # assertion.
    expected = Counter()
    for code, n in grand_before.items():
        expected[cw[code]] += n
    mismatch = {c: (expected.get(c, 0), grand_after.get(c, 0))
                for c in set(expected) | set(grand_after)
                if expected.get(c, 0) != grand_after.get(c, 0)}
    if mismatch:
        all_problems.append(f"AGGREGATE MISMATCH (expected, actual): {mismatch}")

    header = [
        f"# OWASP LLM Top 10 2025 -> 2026 migration delta",
        "",
        f"- generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        f"- mode: {'APPLY' if args.apply else 'DRY RUN'}",
        f"- crosswalk: `mappings/owasp_llm_2025_to_2026.json` (bijective)",
        f"- files touched: {len(planned)}",
        f"- total code assignments migrated: {sum(grand_before.values())}",
        "",
        "## Aggregate: all migrated inputs",
        "",
        "| 2025 code | 2025 name | count | -> | 2026 code | 2026 name | count |",
        "|---|---|---:|---|---|---|---:|",
    ]
    spec = json.loads(CROSSWALK_PATH.read_text(encoding="utf-8"))["crosswalk"]
    for old in sorted(spec):
        new = spec[old]["to"]
        header.append(
            f"| {old} | {spec[old]['name_2025']} | {grand_before.get(old, 0)} | -> | "
            f"{new} | {spec[old]['name_2026']} | {grand_after.get(new, 0)} |"
        )
    header += [
        "",
        f"**Totals** — before: {sum(grand_before.values())}, "
        f"after: {sum(grand_after.values())} "
        f"({'MATCH' if sum(grand_before.values()) == sum(grand_after.values()) else 'MISMATCH'})",
        "",
        "Every other field is asserted unchanged per file below; entry counts and",
        "ID sets are compared explicitly. Unintended deltas are defects, not noise.",
        "",
        "## Per-file field-level delta",
        "",
    ]

    report = "\n".join(header + lines)
    if all_problems:
        report += "\n## PROBLEMS\n\n" + "\n".join(f"- {p}" for p in all_problems) + "\n"
    else:
        report += "\n## PROBLEMS\n\nNone. Only `owasp_llm` / `owasp_entries` changed;\n" \
                  "entry counts, ID sets and all other fields are identical.\n"

    if args.report:
        Path(args.report).write_text(report, encoding="utf-8")
        print(f"[report] {args.report}")
    else:
        print(report)

    if all_problems:
        print("\nFAILED: problems found; refusing to apply.", file=sys.stderr)
        return 1

    if not args.apply:
        print(f"\nDRY RUN — {len(planned)} files would change. Re-run with --apply.")
        return 0

    stamp.setdefault("migrations", {}).setdefault(MIGRATION_ID, {})
    for path, text, sha_before in planned:
        # newline="" so the LF endings in `text` are written verbatim. Plain
        # write_text() on Windows translates \n -> \r\n, which rewrites every
        # line ending in the file for a change that touches a handful of them.
        with open(path, "w", encoding="utf-8", newline="") as fh:
            fh.write(text)
        rel = path.relative_to(ROOT).as_posix()
        stamp["migrations"][MIGRATION_ID][rel] = {
            "applied": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "sha256_before": sha_before,
            "sha256_after": sha256(path),
        }
    STAMP_PATH.write_text(json.dumps(stamp, indent=2) + "\n", encoding="utf-8")
    print(f"\nAPPLIED to {len(planned)} files. Stamp: {STAMP_PATH.relative_to(ROOT)}")
    print("Next: `make build` to regenerate data/*.json from the migrated inputs.")
    return 0


def verify(path: Path, cw: dict[str, str]) -> int:
    """Post-build check: compare a built file's census against the expected
    image of the recorded pre-migration census."""
    obj = json.loads(path.read_text(encoding="utf-8"))
    got = census(obj)
    print(f"{path}: {sum(got.values())} code assignments")
    for code in sorted(got):
        print(f"  {code} {got[code]}")
    stamp = load_stamp()
    exp = stamp.get("expected_built_census", {}).get(path.name)
    if not exp:
        print("\n(no expected census recorded for this file; census printed only)")
        return 0
    if Counter(exp) == got:
        print("\nMATCH: built census equals the expected image of the pre-migration census.")
        return 0
    print(f"\nMISMATCH: expected {dict(sorted(exp.items()))}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
